src/pocketmine/lang/locale/ind.ini
add bahasa indonesia on language
=> Add bahasa indonesia

src/pocketmine/Server.php, src/pocketmine/level/generator/biome/BiomeSelector.php, src/pocketmine/level/generator/normal/Normal.php
Fixed Normal Generator and use Normal2 as default generator.
=> Fixed Generator Error (issue #30)

src/pocketmine/network/protocol/LoginPacket.php
=> Fixed LoginPacket, should resolve #65

src/pocketmine/Player.php
Fix syntax error Player.php
https://github.com/GenisysPro/GenisysPro/issues/97
I have tested the code and it works.
=> Fix syntax error Player.php

src/pocketmine/network/protocol/CameraPacket.php
=> Change getName()

src/pocketmine/block/Sponge.php
Sponges
I have tested the code and it works
=> Working Sponges

src/pocketmine/block/Hopper.php, src/pocketmine/entity/XPOrb.php
Hoppers and bug.
I have tested the code and it works.
=> Fix #184 And Add Limited Creative To Hoppers

README.md
its not very good 
het is not so goed
=> dutch translate

src/pocketmine/Player.php
Fix title duration
Because of title duration bug
I have tested and it works
=> Fixed Title Duration bug

src/pocketmine/resources/genisys_fra.yml
=> Fix my langage x)

src/pocketmine/network/protocol/ChangeDimensionPacket.php, src/pocketmine/network/protocol/LoginPacket.php, src/pocketmine/network/protocol/ResourcePackClientResponsePacket.php, src/pocketmine/network/protocol/ResourcePacksInfoPacket.php, src/pocketmine/resourcepacks/ZippedResourcePack.php
Fixed ResourcePacks, LoginPacket, etc.
=> Network issues fixing

README.md
=> Add Russian language

src/pocketmine/network/protocol/Info.php
=> Update mcpe version, so delete old version.

.gitignore, resource_packs/resource_packs.yml, src/pocketmine/Server.php, src/pocketmine/block/Bed.php, src/pocketmine/level/Level.php, src/pocketmine/level/generator/ender/Ender.php, src/pocketmine/level/generator/ender/biome/EnderBiome.php, src/pocketmine/level/generator/ender/populator/EnderPilar.php, src/pocketmine/network/protocol/ChangeDimensionPacket.php
I added ender.
Also, I changed several files with warnings that phpstorm has issued. I apologize for my code style.
All tested, but I have bugs with chunks.
=> Trying to add ender world

src/pocketmine/block/EndRod.php
I wrote there what this pull request will do:https://github.com/GenisysPro/GenisysPro/pull/270
I saw the changes from pmmp and I wrote them.Is it better now?
=> Fully placeable endrod from pmmp

src/pocketmine/item/Bed.php
Added colorful beds
Not found colorful beds
Tested. And working
=> Add colorful bed items

src/pocketmine/entity/Shulker.php
Not found other types
-.-
Tested. Working
=> Add colorful shulkers

src/pocketmine/entity/ElderGuardian.php
Not found elder flag
Hmm
Tested working
=> Add elder data fla

src/pocketmine/entity/Ilama.php
Lama types
Lamas
Tested. Working
=> Add other lama types

README.md
See the title. Most likely problems because of the Cyrillic alphabet.
=> Fixed clickable link

src/pocketmine/level/sound/NoteblockSound.php
Noteblock instrument
Noteblock sound instrument buggy
Tested.working
=> Fixed NoteblockSound instrument bug

src/pocketmine/command/defaults/BanCommand.php
Issue https://github.com/GenisysPro/GenisysPro/issues/304 Fixed.
I have tested it.
=> Ban command fixed, Close #304

src/pocketmine/block/Anvil.php
Fix https://github.com/GenisysPro/GenisysPro/issues/294 1/2
I have tested it.
=> Fix Anvil place sound.

src/pocketmine/Player.php
Fixed some bug and added ItemFrameDropItemEvent that was not used before.
=> Fixed some bugs

src/pocketmine/lang/locale/deu.ini
I updated some typing mistakes and bad translations from ENG -> DEU
Bad translations/Typing mistakes
=> Updated some bad translations | deu.ini

.gitignore
=> Some updates

src/pocketmine/block/Beacon.php, src/pocketmine/block/BurningFurnace.php
=> Fix bug with block entity

src/pocketmine/Server.php, src/pocketmine/block/Beacon.php, src/pocketmine/block/Sponge.php, src/pocketmine/resources/genisys_chs.yml, src/pocketmine/resources/genisys_eng.yml, src/pocketmine/resources/genisys_fra.yml, src/pocketmine/resources/genisys_jpn.yml
Added a new parameter that allows you to enable and disable the capabilities of the sponge
=> Add a new parameter.

src/pocketmine/inventory/ChestInventory.php, src/pocketmine/item/FlintSteel.php
=> add some missing sounds from pmmp

src/pocketmine/Server.php, src/pocketmine/block/Block.php, src/pocketmine/level/Level.php, src/pocketmine/level/LightUpdate.php, src/pocketmine/level/SkyLightUpdate.php, src/pocketmine/level/format/Chunk.php
This PR should completely remove shadows from the map, but there may be a load on the weak machines that use Genisys Pro.
Everything is tested on old and new chunks.
=> Light error fixed.

src/pocketmine/level/Level.php
=> fixed errors in Level.php

README.md
I fixed some Japanese errors and Markdown errors in the Japanese section.
There is some Japanese errors and Markdown errors in the Japanese section.
Only check if the Markdown is rendered correctly or not.
=> Fixes some about the Japanese section

src/pocketmine/resources/genisys_jpn.yml
=> translation japanese

composer.json
Add support for Jenkins server.
It's help our jenkins server to generate builds
**NONE**
=> Add support for Jenkins server

README.md
Any other major issues to add to the To-Do list?
=> Update README.md To-Do list

src/pocketmine/Player.php
Instead of droping item, just send them back to inventory and delete items stuck in floating inventory.
Please test before merging, because I don't know if this is desired solution you wanna, and who knows, it may give errors.
I used this code on Elywing, long ago.
-----
Please reformat code for me. My Microsoft Edge glitch with browser editor :(  ....
=> THIS SHOULD STOP DROPS

src/pocketmine/Server.php
=> Creating new methods for compatibility of plug-ins with different kernels

src/pocketmine/level/sound/BlockPlaceSound.php
Fix BlockPlaceSound
Fixing
Tested. Working
=> Fix BlockPlaceSound

src/pocketmine/level/Level.php
Add blockplacesound
Add
Tested.working
=> Add BlockPlaceSound in useItemOn

src/pocketmine/item/Item.php
=> Fix Item::setLore(array $lore)

src/pocketmine/Player.php
=> Enable use of Elytra

src/pocketmine/Player.php
Partially correct the bug with a display of the reason.
Yes, it works, but when I kick the player's reason and cannot see. If I use `$e->getPlayer()->close("", "test");` it works
=> Fixed bug with close

src/pocketmine/Player.php, src/pocketmine/entity/Effect.php
=> Add Levitation effect

src/pocketmine/Server.php
Forgot to add after update version....
=> Added new feature broadcastTitle()

src/pocketmine/Player.php
=> Fix issue #640

src/pocketmine/command/defaults/EnchantCommand.php, src/pocketmine/lang/locale/deu.ini
It lost too in other language files but i can only german xD
=> Lost maxEnchant message

src/pocketmine/entity/Llama.php
Fix #702 
The change is too small.
=> Hm...  fix.

src/pocketmine/level/Level.php
Correcting crash when getting the name of the world when it is unloaded.
Yes! All nice work.
=> Correcting crash when getting the name of the world when it is unloaded.

src/pocketmine/Player.php
=>  It call bug, when in command not permissions

src/pocketmine/level/Explosion.php
Tnt explosion sound was missing.I added code from pmmp and now someone can listen a tnt exploding.(bad english maybe)
=> Fix explosion sound

src/pocketmine/entity/Entity.php
Correction of NametagAlwaysVisible. The value was not saved.
In test...
=> Correction of NametagAlwaysVisible. The value was not saved.

src/pocketmine/Player.php
if you add if , on send armorcontent, it will glitch.
I tested it but please test before merging for security purpose.
FIXED ARMOR GLITCH WERE IT SHOW YOU DONT HAVE IT, AND REAPEAR AFTER U GET HIT.
=> Dont add IF on sendarmor

src/pocketmine/Server.php
Taken from a W.I.P. Build of Leveryl...
And get_calling_class() is from https://stackoverflow.com/a/6927569/7126351
Bypass SpoonDetector
1. Download the SpoonDetector Class from https://github.com/Falkirks/spoondetector/blob/master/src/spoondetector/SpoonDetector.php
2. Use the code below with a plugin:
```php
if(SpoonDetector::isThisSpoon()){
SpoonDetector::printSpoon($this);
}
```
3. If it doesn't display the message and The plugin doesn't disable itself... It Worked! 😄
=> Bypass SpoonDetector xD

src/pocketmine/block/DragonEgg.php
Now dragon egg can fall.I tested and works.
=> Fallable dragon egg

src/pocketmine/item/enchantment/Enchantment.php
=> Update Enchantment.php # Fix registerEnchantment error when enchant already exists

src/pocketmine/lang/locale/kor.ini
Add Korean's missing translation
Complete test
=> Add Korean's missing translation

src/pocketmine/Player.php
=> Fix no message $player->close , tested!

src/pocketmine/Player.php
Added Level spunds coming from mcpe client
Tested and working
=> Added LevelSounds coming from client

src/pocketmine/entity/ThrownPotion.php
Desc. here:https://github.com/GenisysPro/GenisysPro/pull/864
The reason I re upload my pr is because I added by mistake some commits in my old pr.
=> fix splash potions color

src/pocketmine/inventory/BaseTransaction.php, src/pocketmine/inventory/Transaction.php
A basic modification to add getSourceItem function to BaseTransaction, It doesn't effect internal transactions.
=> Add getSourceItem to base transactiom

src/pocketmine/Player.php
So crafting inventory will also get cleared with the player inventory on death!
Tested
=> Empty floating inventory on death!

README.md
i translated most of the README.md to greek! i have you accept this addition!
it will help alot of greek people that want to use GenisysPro!
thx,
nik
=> Added Greek language

src/pocketmine/network/mcpe/protocol/ProtocolInfo.php
=> 1.1.7 comming

src/raklib/server/Session.php
=> Fixed raklib crash
